version: "3.7"

services:

  postgres_cadastro:

    container_name: postgres_cadastro_ifood

    image: postgres:12.2

    environment:

      POSTGRES_USER: marketplace

      POSTGRES_PASSWORD: marketplace
    ports:

      - "5433:5433"